trailingComma: "es5"
semi: false
singleQuote: false
jsxSingleQuote: false
printWidth: 160
tabWidth: 2
overrides:
    - files: "package.json"
      options:
          tabWidth: 2
    - files: "*.yaml"
      options:
          tabWidth: 4
    - files: "*.md"
      options:
          tabWidth: 2
